server:
  port: 12000

spring:
  config:
    activate:
      on-profile: dev
  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/hkjin?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

netty:
  tcp-port: 12001
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100