version: '3.8'

services:
  # Kafka Broker 0 (Controller + Broker)
  kafka00:
    image: confluentinc/cp-kafka:latest
    hostname: kafka00
    container_name: kafka00
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "10000:10000"  # 외부 접근용 EXTERNAL Listener
    environment:
      # KRaft 설정
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka00:9093,1@kafka01:9093,2@kafka02:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners 설정
      KAFKA_LISTENERS: PLAINTEXT://kafka00:9092,CONTROLLER://kafka00:9093,EXTERNAL://0.0.0.0:10000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka00:9092,EXTERNAL://localhost:10000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # 클러스터 ID (모든 브로커에서 동일해야 함)
      CLUSTER_ID: 'HsDKs916UmQq7Y5E6bNlw'

      # 복제 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_IN_SYNC_REPLICAS: 2

      # 토픽 자동 생성 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 4

      # 성능 최적화
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824  # 1GB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      # JVM 힙 메모리 설정
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

    volumes:
      - kafka00:/confluence/kafka
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafka Broker 1 (Controller + Broker)
  kafka01:
    image: confluentinc/cp-kafka:latest
    hostname: kafka01
    container_name: kafka01
    restart: unless-stopped
    ports:
      - "9093:9092"
      - "10001:10001"
    environment:
      # KRaft 설정
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka00:9093,1@kafka01:9093,2@kafka02:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners 설정
      KAFKA_LISTENERS: PLAINTEXT://kafka01:9092,CONTROLLER://kafka01:9093,EXTERNAL://0.0.0.0:10001
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092,EXTERNAL://localhost:10001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # 클러스터 ID
      CLUSTER_ID: 'HsDKs916UmQq7Y5E6bNlw'

      # 복제 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_IN_SYNC_REPLICAS: 2

      # 토픽 자동 생성 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 4

      # 성능 최적화
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      # JVM 힙 메모리 설정
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

    volumes:
      - kafka01:/confluence/kafka
    networks:
      - kafka_network
    depends_on:
      - kafka00
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafka Broker 2 (Controller + Broker)
  kafka02:
    image: confluentinc/cp-kafka:latest
    hostname: kafka02
    container_name: kafka02
    restart: unless-stopped
    ports:
      - "9094:9092"
      - "10002:10002"
    environment:
      # KRaft 설정
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka00:9093,1@kafka01:9093,2@kafka02:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners 설정
      KAFKA_LISTENERS: PLAINTEXT://kafka02:9092,CONTROLLER://kafka02:9093,EXTERNAL://0.0.0.0:10002
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:9092,EXTERNAL://localhost:10002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # 클러스터 ID
      CLUSTER_ID: 'HsDKs916UmQq7Y5E6bNlw'

      # 복제 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_IN_SYNC_REPLICAS: 2

      # 토픽 자동 생성 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 4

      # 성능 최적화
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      # JVM 힙 메모리 설정
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

    volumes:
      - kafka02:/confluence/kafka
    networks:
      - kafka_network
    depends_on:
      - kafka00
      - kafka01
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

# network bridge
networks:
  kafka_network:
    driver: bridge

# kafka metadata volume
volumes:
  kafka00:
    driver: local
  kafka01:
    driver: local
  kafka02:
    driver: local