server:
  port: 9400

spring:
  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/redis_lab?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        jdbc:
          # batch_size: 30 # 배치 크기 설정
    defer-datasource-initialization: true
    open-in-view: false

logging:
  level:
    org.hibernate.orm.connections.pooling: warn
    org.springframework.data.redis: debug # spring data redis 명령어 로그 -> SET,HSET,DEL
    io.lettuce.core.protocol.DefaultEndpoint: debug # Redis 서버와 실제 요청/응답 확인