server:
  port: 9200
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/kafka_lab?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true

  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
    consumer:
      auto-offset-reset: earliest
      properties:
        metadata.max.age.ms: 30000
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        request.timeout.ms: 30000

hkjin:
  kafka:
    topics:
      realtime-transaction-batch:
        name: "realtime-transaction-batch"
        group-id: "realtime-transaction-batch-group"
      audit:
        name: "toy-audit"
        group-id: "payment-audit"
      log:
        name: "payment-log"
        group-id: "payment-log-process-group"
