server:
  port: 9200
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/kafka_lab?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  kafka:
    bootstrap-servers: "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094"
    consumer:
      auto-offset-reset: earliest

hkjin:
  kafka:
    topics:
      realtime-transaction-batch:
        name: "realtime-transaction-batch"
        group-id: "realtime-transaction-batch-group"
      audit:
        name: "toy-audit"
        group-id: "payment-audit"