server:
  port: 9200

spring:
  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/ddd?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  kafka:
    boostrap-servers: "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094"


hkjin:
  kafka:
    auto-offset-reset: earliest
    topics:
      realtime-transaction-batch:
        name: "realtime-transaction-batch"
        group-id: "realtime-transaction-batch-group"