server:
  port: 8300

spring:
  # db
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:jpa'
    username: hkjin
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console # 접속: localhost:8300/h2-console
  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  # vault
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: https
      authentication: token
      token: 1234567890000
      connection-timeout: 5000
      read-timeout: 15000